#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ "$#" != "4" ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 0
fi
PATH_FILE=$1
IP=$2
USERNAME=$3
PATH_SSH=$4
scp -i "$PATH_SSH" -o StrictHostKeyChecking=no "$PATH_FILE" "$USERNAME"@"$IP":~/
