#!/usr/bin/env bash
# Install nginx on my server
sudo apt update -y && sudo apt upgrade -y
sudo apt install -y nginx
sudo echo "Hello world" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
