#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
apt update -y && apt upgrade -y
apt install nginx -y
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/listen \[::\]:80 default_server;/a\\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/QH2-TGUlwu4 permanent;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

sed -i "/then fall back to displaying a 404./a\\\t\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

service nginx restart
