#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt update -y
apt-get install haproxy -y

echo "ENABLED=1" >> /etc/default/haproxy

haproxy_cfg="\nbackend web-backend\n\tbalance roundrobin\n\tserver 3684-web-01 35.231.250.123:80 check\n\tserver 3684-web-02 34.148.86.204:80 check\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"

echo -e "$haproxy_cfg" >> /etc/haproxy/haproxy.cfg

service haproxy restart
