#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.
if [ $# -eq 0 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
elif [ $# -eq 1 ]; then
adress=$*
ping "$adress" -c 5
fi
