#!/usr/bin/env bash
# Display "Best School" 10 times except for 9 which will Display an extra "Hi"
i=1
while [ $i -le 10 ]; do
  echo "Best School"
  if [ $i -eq 9 ]; then
    printf "Hi\n"
  fi
  (( i++ ))
done
