#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.
FILE=/home/vagrant/holberton/github/holberton-system_engineering-devops/0x04-loops_conditions_and_parsing/school
if [ -e $FILE ]; then
  echo "school file exists"
  if [ -s $FILE ]; then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi
  if [ -f $FILE ]; then
    echo "school file is a regular file"
  fi
else
  echo "school file does not exist"
fi


