#!/bin/bash
# Run Nginx as Nginx
sudo pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
echo 'user nginx;' >> /etc/nginx/nginx.conf
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
